var a=33;
var b=44;
console.log(a+=b);
console.log(a-=b);
console.log(a*=b);
console.log(a/=b);
console.log(a%=b);
let x=66;
let y=88;
console.log(x&y);
console.log(x|y);
console.log(x^y);
console.log(x>>y);
console.log(x<<y);
var a1=123;
var b1=144;
console.log(a1+=b1);
console.log(a1-=b1);
console.log(a1*=b1);
console.log(a1/=b1);
console.log(a1%=b1);
let L=66;
let m=88;
console.log(L&m);
console.log(L|m);
console.log(L^m);
console.log(L>>m);
console.log(L<<m);

